package interception.java.binds.key.binds;

import static interception.java.binds.key.binds.InterceptionMouseState.*;

public class InterceptionFilterMouseState {
    public static int FILTER_MOUSE_NONE = 0x0000,
            FILTER_MOUSE_ALL = 0xFFFF,

    FILTER_MOUSE_LEFT_BUTTON_DOWN = MOUSE_LEFT_BUTTON_DOWN,
            FILTER_MOUSE_LEFT_BUTTON_UP = MOUSE_LEFT_BUTTON_UP,
            FILTER_MOUSE_RIGHT_BUTTON_DOWN = MOUSE_RIGHT_BUTTON_DOWN,
            FILTER_MOUSE_RIGHT_BUTTON_UP = MOUSE_RIGHT_BUTTON_UP,
            FILTER_MOUSE_MIDDLE_BUTTON_DOWN = MOUSE_MIDDLE_BUTTON_DOWN,
            FILTER_MOUSE_MIDDLE_BUTTON_UP = MOUSE_MIDDLE_BUTTON_UP,

    FILTER_MOUSE_BUTTON_1_DOWN = MOUSE_BUTTON_1_DOWN,
            FILTER_MOUSE_BUTTON_1_UP = MOUSE_BUTTON_1_UP,
            FILTER_MOUSE_BUTTON_2_DOWN = MOUSE_BUTTON_2_DOWN,
            FILTER_MOUSE_BUTTON_2_UP = MOUSE_BUTTON_2_UP,
            FILTER_MOUSE_BUTTON_3_DOWN = MOUSE_BUTTON_3_DOWN,
            FILTER_MOUSE_BUTTON_3_UP = MOUSE_BUTTON_3_UP,

    FILTER_MOUSE_BUTTON_4_DOWN = MOUSE_BUTTON_4_DOWN,
            FILTER_MOUSE_BUTTON_4_UP = MOUSE_BUTTON_4_UP,
            FILTER_MOUSE_BUTTON_5_DOWN = MOUSE_BUTTON_5_DOWN,
            FILTER_MOUSE_BUTTON_5_UP = MOUSE_BUTTON_5_UP,

    FILTER_MOUSE_WHEEL = MOUSE_WHEEL,
            FILTER_MOUSE_HWHEEL = MOUSE_HWHEEL,

    FILTER_MOUSE_MOVE = 0x1000;
}
